source("R/00_setup.R")
source("R/01_download_nhanes_files.R")
source("R/02_build_analysis_dataset.R")
source("R/03_journal_facing_models.R")
source("R/04_verify_manuscript_values.R")
source("R/06_session_info.R")
